# Generated by Django 3.1 on 2020-11-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='number2',
            field=models.IntegerField(default=0, verbose_name='ID'),
        ),
    ]
